services:
  game:
    build: .
    ports:
      - "8001:8001" 
      - "8808:8808"
    volumes:
      - .:/code
    environment:
      - RUST_LOG=info
    depends_on:
      - cache
  cache:
    image: redis:6.2-alpine
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning

